### ISSUE TITLE
Windows executable

### ISSUE THREAD

**Issue by FernandezR** [RikudouSage/mangastream-downloader#2]
I was checking out your downloader and noticed that it currently isn't downloading the images correctly. Essentially the images are empty. I take a look it if I have time, but wanted to let you know.

**Comment by 98115** [comment]
having the same problem as FernandezR all the manga downloads but the images are empty

**Comment by RikudouSage** [comment]
Thank you, I will look into it.

**Comment by RikudouSage** [comment]
This issue is fixed now and downloading should work again. Right now there's only the zipped version, when I have time I'll add the single exe file.
